module.exports = [
   {
      loanDate: new Date("2024-04-01"),
      dueDate: new Date("2024-04-15"),
      bookId: 1,
      userId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 2,
      loanDate: new Date("2024-04-03"),
      dueDate: new Date("2024-04-17"),
      bookId: 2,
      userId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 3,
      loanDate: new Date("2024-04-05"),
      dueDate: new Date("2024-04-19"),
      bookId: 3,
      userId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 4,
      loanDate: new Date("2024-04-07"),
      dueDate: new Date("2024-04-21"),
      bookId: 4,
      userId: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 5,
      loanDate: new Date("2024-04-09"),
      dueDate: new Date("2024-04-23"),
      bookId: 5,
      userId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 6,
      loanDate: new Date("2024-04-11"),
      dueDate: new Date("2024-04-25"),
      bookId: 6,
      userId: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 7,
      loanDate: new Date("2024-04-13"),
      dueDate: new Date("2024-04-27"),
      bookId: 7,
      userId: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 8,
      loanDate: new Date("2024-04-15"),
      dueDate: new Date("2024-04-29"),
      bookId: 8,
      userId: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 9,
      loanDate: new Date("2024-04-17"),
      dueDate: new Date("2024-05-01"),
      bookId: 9,
      userId: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 10,
      loanDate: new Date("2024-04-19"),
      dueDate: new Date("2024-05-03"),
      bookId: 10,
      userId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
];
